### ISSUE TITLE
`next`ing over ActiveRecord method calls continues until next breakpoint

### ISSUE THREAD

**Issue by soberstadt** [deivid-rodriguez/byebug#550] opened 2019-03-20 03:47 UTC
## Problem description

Like #481, I'm having issues using `next` except this issue is only one 2.6 opposed to 2.5 that #481 has. When trying to `next` over calls in rails, it jumps to the next breakpoint (or to some other place if you don't have one). I don't know what other types of methods cause it to advance like this, but ActiveRecord calls have proven to cause it. I tried method delegation like #481, but I couldn't make a basic class example.

## Steps to reproduce the problem

Here is a basic example I have created: https://github.com/soberstadt/byebug-issue-example

If you change to ruby 2.6.1, run `bundle exec rspec`. And `next` once is halts.

<img width="546" alt="Screen Shot 2019-03-19 at 11 32 57 P M" src="https://user-images.githubusercontent.com/1080613/54657689-d331f480-4aa0-11e9-8631-24bca916f923.png">
<img width="951" alt="Screen Shot 2019-03-19 at 11 32 16 PM" src="https://user-images.githubusercontent.com/1080613/54657698-d9c06c00-4aa0-11e9-858e-a1616645a9a2.png">
<img width="544" alt="Screen Shot 2019-03-19 at 11 46 38 PM" src="https://user-images.githubusercontent.com/1080613/54657791-420f4d80-4aa1-11e9-918e-5f4e0a46a180.png">

**Comment by soberstadt** [comment] 2019-04-11 14:27
@deivid-rodriguez any thoughts on this? I'm really missing debugging with byebug :D

**Comment by stwr667** [comment] 2019-05-01 12:41
I'm having the same issue too with RUBY_VERSION `2.6.2`.

**Comment by deivid-rodriguez** [comment] 2019-05-02 07:55
I'll try to have a look at this next week, sorry for the delay!

**Comment by canoeberry** [comment] 2019-08-15 23:39
I have been unable to reliably debug for a very long time and I think it's related to this issue: https://bugs.ruby-lang.org/issues/15303. I first noticed this when I switched to ruby 2.5.3.

It has been fixed but I am not understanding how to tell when this change (removing the tail recursion optimisation that causes this) will be back ported to a released version of ruby. I am not even 100% sure how to tell if that will happen or whether it did happen, although the issue is still a problem in 2.5.5.

I feel like a newbie not knowing how this works. Can you shed any light on whether this is that problem?

**Comment by deivid-rodriguez** [comment] 2019-08-16 07:36
Oh god, I forgot again, too busy with other stuff...

That PR workarounded the issue for a very common case in the standard library by not using tailcall optimization there, but the issue with tail recursion is still there, so it might indeed be what we're seeing.

I'll try to isolate a small reproduction to confirm, and if that's the issue, I'll try to persuade ruby-core to fix this the right way.

Again, I'm sorry I dropped the ball here :grimacing:.

**Comment by canoeberry** [comment] 2019-08-16 17:01
Wow - thanks. I am glad I asked.

Even if there were just a way to disable that particular optimisation, that would at least make it possible to get work done while debugging.

Anyway - thanks. Good luck. Fingers crossed. Etc.

**Comment by deivid-rodriguez** [comment] 2019-08-28 21:01
Hi everyone. So I bisected this today and the culprit is https://github.com/ruby/ruby/commit/1bc6c3f40777ca10d8e7df38b775b0bb81a25881, which pointed me to the original ticket: https://bugs.ruby-lang.org/issues/15578.

Luckily enough, the fix has been backported and release _today_: https://www.ruby-lang.org/en/news/2019/08/28/ruby-2-6-4-released/.

So I think we're good here. I'll update the README to point this out!

**Closed by deivid-rodriguez** 2019-08-28 21:01 UTC

**Comment by canoeberry** [comment] 2019-08-29 21:09
Life changing. Cheers mate!

**Comment by stwr667** [comment] 2019-09-04 05:30
Fantastic @deivid-rodriguez thank you. Upgraded to 2.6.4 just now and it works!
