### ISSUE TITLE
You want to finish 2 frames, but stack size is only -3

### ISSUE THREAD

**Issue by nritholtz** [deivid-rodriguez/byebug#127] opened 2015-03-11 20:31 UTC
I'm currently pointing to master, specifically commit '7c8c0db25f3efe5878477449c5b9e070b41beabe'

Randomly when starting or in the middle of using byebug inside my cucumber/capybara steps, I get the error
```
You want to finish 2 frames, but stack size is only -3
```

The stack trace isn't really showing anything useful, except at some points along the way the negative number at the end of the error message, keeps increasing until the thread (test) is finished.

Unfortunately I don't have a sample app to provide, since this proprietary project. However, if necessary and I can find some time to see if I can scrape one together.

Any ideas?

**Comment by nritholtz** [comment] 2015-03-11 20:34
*Note*: This occurs usually after I enter `c` for the first breakpoint, and the error is raised for every subsequent `byebug` call.

**Comment by deivid-rodriguez** [comment] 2015-03-11 22:39
This is really weird @nritholtz . I do need a sample app, otherwise I'm totally lost here... :(

**Comment by jbrodie** [comment] 2015-03-17 23:46
You want to finish 2 frames, but stack size is only -373
I have seen many different levels, and can probably reproduce them more then not through out a night of doing development work.

What I can tell you is Rails 4.1.6, Ruby 2.1.2-p95, let me know what sort of details will help and I will copy and paste them all in next time I get this hit.

**Comment by deivid-rodriguez** [comment] 2015-03-18 02:19
Ok, this is definitely a regression, sorry about that. I'll fix it soon.

**Comment by jbrodie** [comment] 2015-03-19 01:04
Let me know if you need anymore details, I am more then happy to produce when I hit the error.

Normally a restart of the server resolves it as well.

**Comment by sofibraun** [comment] 2015-03-19 03:19
+1 same error

**Comment by deivid-rodriguez** [comment] 2015-03-20 18:18
Guys, I'm pretty sure the offending commit is [this one](https://github.com/deivid-rodriguez/byebug/commit/aaadb8757f46fe0a24cea762c6c46c940cf59b9d), but I'd like to reproduce this myself cause I think that commit is the way to good and I wouldn't like it reverted. So I'd like to properly fix this.

Does anyone have a sample app that exhibits this behavior? If not, specifyinf `set verbose` in your `.byebugrc` file and copying the output when you hit the error in a gist can be useful too.

**Comment by jbrodie** [comment] 2015-03-20 19:03
I will be working on my project throughout the weekend and will more then likely hit it so I will add and post back.

**Comment by deivid-rodriguez** [comment] 2015-03-20 23:24
:+1: If you can copy paste some code context around your `byebug` call, that'd be great too.

**Comment by jbrodie** [comment] 2015-03-21 02:43
Is there anyway to have the debug information sent to a separate log file?  Just tested it with a debugger point and have been waiting 5 minutes for the code to continue!

**Comment by deivid-rodriguez** [comment] 2015-03-21 13:11
No... can you use shell redirections?

**Comment by ketuls** [comment] 2015-03-26 16:01
+1. Error stacktrace pasted here. http://pastebin.com/94kngDxc

**Comment by deivid-rodriguez** [comment] 2015-03-26 19:19
Can someone hitting the issue try against the `issue_127` branch and tell me if the bug is fixed there?

**Comment by jbrodie** [comment] 2015-03-26 19:55
I will update to that branch when working tonight and let you know if I encounter it again.

**Comment by deivid-rodriguez** [comment] 2015-03-26 19:56
:+1:

**Comment by epergo** [comment] 2015-03-26 20:03
Hi all, I have tried your fix and I think it works, I have been suffering that bug in a concrete place inside my app and now it works like a charm. Lets see what others say about their tests.

**Comment by ketuls** [comment] 2015-03-26 20:57
I am new to Ruby and ROR. Below are my steps,

1) I have download the code with git clone.
2) Build the gem and installed it.
dev@ketuls ~/byebug> gem build byebug.gemspec 
  Successfully built RubyGem
  Name: byebug
  Version: 4.0.3
  File: byebug-4.0.3.gem
dev@ketuls ~/byebug> gem install byebug-4.0.3.gem 
Building native extensions.  This could take a while...
Successfully installed byebug-4.0.3
1 gem installed

3) Added this line to gemfile of rails.
# Use debugger
gem 'byebug', '4.0.3', group: [:development, :test]  

4)  bundle install | grep 'bye'
Using byebug 4.0.3
 
Hope the above is the correct way to do...When i run the application, I am still getting a bug

"/home/dev/.gem/ruby/2.1.0/gems/byebug-4.0.3/lib/byebug/attacher.rb:15:in `step_out'......./home/dev/.gem/ruby/2.1.0/gems/byebug-4.0.3/lib/byebug/attacher.rb:15:in `attach'......./home/dev/.gem/ruby/2.1.0/gems/byebug-4.0.3/lib/byebug/attacher.rb:26:in `byebug'......./home/dev/dwb/housing.images/app/workers/similar_flats_worker.rb:13:in `perform'

**Comment by epergo** [comment] 2015-03-26 21:04
You can do the following, I guess:
gem 'byebug', :git => 'https://github.com/deivid-rodriguez/byebug.git'

Easier.

**Comment by deivid-rodriguez** [comment] 2015-03-26 21:05
To try the fix, add this to your gemfile

    gem 'byebug', github: 'deivid-rodriguez/byebug', branch: 'issue_127'

**Comment by ketuls** [comment] 2015-03-26 21:08
Thanks for the cool way. Ignore my comments because i forgot to switch branch and was using code from master.

**Comment by deivid-rodriguez** [comment] 2015-03-26 21:12
@ketuls No problem, let me know if it works for you.

**Comment by ketuls** [comment] 2015-03-26 23:58
Yuppy . I tried around 5 times & it works fine for me.

**Comment by deivid-rodriguez** [comment] 2015-03-27 17:13
@nritholtz @jbrodie @sofibraun Have you tried the patch? Did you find any problems?

**Comment by nritholtz** [comment] 2015-03-27 17:41
@deivid-rodriguez Unfortunately I haven't been able to find an isolated reproducible scenario. I will let you know if it comes up again in testing, but for now, I will have to defer to the others.

**Comment by jbrodie** [comment] 2015-03-27 19:03
I didn't see any issues last night and will continue to watch tonight and throughout the weekend.

**Comment by deivid-rodriguez** [comment] 2015-03-27 20:38
I've merged the branch and released a new version with the fix. Thanks to all for the reports.

**Comment by jkopczyn** [comment] 2015-04-10 23:06
Was this supposed to be fixed in 4.0.5? I'm still seeing it; not every time but frequently. Rails 4.1.6, Ruby 2.1.2-p95, and like jbrodie restarting the server generally resolves the problem.

**Comment by deivid-rodriguez** [comment] 2015-04-11 18:25
Well, I was never able to reproduce the bug, so I guess this was likely to happen. If you want to help, point me to an app where I can reproduce this and tell me how.

**Comment by deivid-rodriguez** [comment] 2015-04-12 12:36
I think this is due to using an outdated Ruby version (including bugs in the TracePoint API).

So I don't plan to include any further fixes unless this is reproduced in either `2.1.5` or `2.2.1`. They are 100% backwards compatible patch level release version, so there's no excuse to upgrade... let alone in development enviroments.

**Closed by deivid-rodriguez** 2015-04-12 12:36 UTC
Labels: bug, needs feedback

**Comment by RichardWigley** [comment] 2015-04-12 15:40
[On the application I was developing, I was able to reproduce the bug while using Ruby 2.1.2-p95 and byebug 4.0.5](https://github.com/BCS-io/letting/commit/fc1863134e04844df8faa46003fbe876f849a521). Upgrading to ruby 2.2.1p85 - has solved this bug for me.

**Comment by deivid-rodriguez** [comment] 2015-04-12 16:09
Cool, thanks @RichardWigley 

@jkopczyn Can you upgrade and confirm this does not affect 2.2.1 or 2.1.5?

**Comment by jkopczyn** [comment] 2015-04-13 14:46
Appears to have worked so far. Will have more definite confirmation over
the next couple days.

**Comment by scottbarrow** [comment] 2015-04-14 02:14
Still seeing this issue occasionally with 
pry-byebug 4.0.5, ruby 2.1.2-p95
will try and find a replicateable pattern

**Comment by deivid-rodriguez** [comment] 2015-04-14 02:34
@scottbarrow Have you read previous messages? Upgrade to `2.1.5` or `2.2.1` and the bug should be gone.

**Comment by kamal-github** [comment] 2015-06-23 05:09
I am using byebug 5.0.0 but still facing this issue.

**Comment by kyprifog** [comment] 2015-06-29 18:32
I am also getting this issue.  It seems to be related to the way that you exit the pry debugger, but I cannot get it to consistently reproduce.  This brings down my debugging session 3 or 4 times within a single bug and is seriously slowing me down so any advice would be appreciated.

**Comment by deivid-rodriguez** [comment] 2015-06-29 18:46
@kyprifog @kamal-github If you still experience this using latest `byebug` master with `ruby 2.2.1` or greater, I'll reopen.

**Comment by derekcannon** [comment] 2015-07-09 10:27
`RuntimeError: You want to finish 3 frames, but stack size is only 1
from /Users/derekcannon/.rvm/gems/ruby-2.2.2/gems/pry-byebug-3.1.0/lib/byebug/processors/pry_processor.rb:24:in `step_out'`

I am getting this error with `ruby 2.2.2p95` and `bye bug 4.0.5` in a single-file Ruby project. I can reproduce this issue consistently by calling a method that hits a pry while already prying. After including `pry_bugbuy` and getting this error, removing the `require` from the .rb file is not enough. I have to uninstall the gem to get pry working normally again.

**Comment by deivid-rodriguez** [comment] 2015-07-09 10:41
More than happy to reopen if you provide a reproduction using latest master with ruby `2.2.1`.

**Comment by derekcannon** [comment] 2015-07-09 10:47
Do you want Ruby `2.2.1` specifically? Bugbye master looks like it's at `5.0.0`. But 'pry-bugbye' wants `4.0.3`. Do I have this information correct?

**Comment by deivid-rodriguez** [comment] 2015-07-09 10:53
Sorry, I meant '2.2.2`. Do you actually need `pry-byebug` to reproduce this?

**Comment by derekcannon** [comment] 2015-07-09 10:56
I double-checked for you. Yes, without it, the same steps I'm using to pry work fine.

**Comment by deivid-rodriguez** [comment] 2015-07-09 11:03
Thanks. So... the repro?

**Comment by YOUConsulting** [comment] 2015-09-25 13:51
Any progress on this?

**Comment by deivid-rodriguez** [comment] 2015-09-27 22:33
@YOUConsulting  The issue is waiting for a reproduction. Your question make me think that you are experiencing the issue too, so it looks like the ball is in your court.

**Comment by YOUConsulting** [comment] 2015-09-28 06:52
@deivid-rodriguez what logs do you want? How can I help :)

**Comment by deivid-rodriguez** [comment] 2015-09-28 11:01
I need a way to reproduce the issue myself using recent rubies. As you can imagine, I can't fix it if I can't see it happening...

**Comment by YOUConsulting** [comment] 2015-09-28 12:21
@deivid-rodriguez  what solved the issue for me specifically is going from the following gems:
  gem 'pry'
  gem 'pry-byebug'
  gem 'pry-stack_explorer'
  gem 'pry-rails'
  gem 'pry-remote'
  gem 'byebug'

pry (0.10.2)
  coderay (~> 1.1.0)
  method_source (~> 0.8.1)
  slop (~> 3.4)
pry-byebug (3.2.0)
  byebug (~> 5.0)
  pry (~> 0.10)
pry-rails (0.3.4)
  pry (>= 0.9.10)
pry-remote (0.1.8)
  pry (~> 0.9)
  slop (~> 3.0)
pry-stack_explorer (0.4.9.2)
  binding_of_caller (>= 0.7)
  pry (>= 0.9.11)


Too currently the following setup:
pry (0.10.2)
      coderay (~> 1.1.0)
      method_source (~> 0.8.1)
      slop (~> 3.4)
    pry-byebug (1.3.3)
      byebug (~> 2.7)
      pry (~> 0.10)
    pry-rails (0.3.4)
      pry (>= 0.9.10)
    pry-remote (0.1.8)
      pry (~> 0.9)
      slop (~> 3.0)
    pry-stack_explorer (0.4.9.2)
      binding_of_caller (>= 0.7)
      pry (>= 0.9.11)


Only problem is that next and step is not working yet, you can follow the progress here: http://stackoverflow.com/questions/32780971/pry-remote-not-triggered-rails-4/32818381#32818381

**Comment by deivid-rodriguez** [comment] 2015-09-28 23:05
I'm totally lost regarding why downgrading the libraries would fix this issue. Are you sure you are posting to the right issue? I think you are refering to https://github.com/deivid-rodriguez/pry-byebug/issues/33

**Comment by YOUConsulting** [comment] 2015-09-29 06:30
Well using the my gems described above also fixed the issue with "You want to finish 2 frames..."

**Comment by kamal-github** [comment] 2015-10-02 18:11
Finally, had to switch to binding.pry

**Comment by luisalima** [comment] 2015-10-27 11:07
I also had the same problem, and using the configuration proposed by @YOUConsulting in [this comment](https://github.com/deivid-rodriguez/byebug/issues/127#issuecomment-143727666) also solved my issue.

**Comment by zenkalia** [comment] 2016-05-24 22:26
i'm seeing this issue in both byebug and binding.pry using ruby 2.3.0

**Comment by deivid-rodriguez** [comment] 2016-05-25 07:28
I'd like to help you people with this issue, but as you can imagine, if I can't see it happening, I can't fix it.

**Comment by derekcannon** [comment] 2016-05-25 07:52
What do you mean "you people"?

**Comment by deivid-rodriguez** [comment] 2016-05-25 07:58
Sorry about my terrible English. I mean "people still facing this issue". What do you think I meant?

**Comment by deivid-rodriguez** [comment] 2016-05-25 08:11
@derekcannon So are you still getting the issue? I asked you for a reproduction 10 months ago and you didn't reply.

**Comment by zenkalia** [comment] 2016-05-25 21:24
i just tried to reproduce this with a simple example and couldn't. i've
even been throwing in a bunch of classes and Tempfiles and haven't been
able to see the crash. i'd send you the original script i'm working on but
you'd need redshift and redis and a dump of cloudfront logs...

**Comment by deivid-rodriguez** [comment] 2016-05-26 11:02
@zenkalia what ruby version are you using? Is it one of the versions recommended in the README?

**Comment by zenkalia** [comment] 2016-05-26 17:31
@deivid-rodriguez i was seeing the issue in 2.3.0 but just upgraded to 2.3.1 and haven't seen the issue again.

**Comment by deivid-rodriguez** [comment] 2016-05-26 18:29
@zenkalia That's weird. I'm not aware of any changes in 2.3.1 that could improve (or worsen) byebug's behaviour...

**Comment by ccutrer** [comment] 2016-10-17 17:38
I just got it with ruby 2.3.1. Unfortunately, I'm running a _huge_ app, so can't easily distill down to a simple test case. It seems to only happen when I'm running a Rails app under pow.cx (i.e. no pty), but works fine when I use `rails server`

**Comment by mahemoff** [comment] 2017-07-04 05:00
FWIW I just saw it for the first time. It was on the console (Ruby 2.3.1 using pry)
(I think it was after I _removed_ the byebug line, then reload!, then ran it again ... though I might be dreaming about that.)

/opt/ruby/gems/2.3.0/gems/byebug-9.0.6/lib/byebug/attacher.rb:19:in `step_out'", /opt/ruby/gems/2.3.0/gems/byebug-9.0.6/lib/byebug/attacher.rb:19:in `attach'", 
/home/proj/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/byebug-9.0.6/lib/byebug/attacher.rb:30:in `byebug'""/Users/mox/prog/player-server/app/models/search/searchkicke

**Comment by hovissimo** [comment] 2019-09-06 01:32
I can reliably reproduce this issue in my regretfully large, regretfully private repo.

ruby 2.3.8p459 (2018-10-18 revision 65136) [x86_64-linux]
Rails 5.0.7.2

Reproduction is as follows,
1. Insert a `byebug` in some app code that will be exercised multiple times by some tests, and run said tests.
2. When byebug breaks, issue `skip`
3. Watch the errors roll in.

Interestingly, the stack size keeps "shrinking" to lower and lower negative numbers.  It seems like some stack size counter is not being properly reset, or perhaps frames are not being accounted for as they are pushed.

Here's a redacted sample: 
![image](https://user-images.githubusercontent.com/6434414/64394469-30980e80-d00b-11e9-8149-3602b9f36487.png)

I can probably provide more details if you can ask for specifics.  A unredacted stack trace won't be available, sorry. :(
