### ISSUE TITLE
Why no `pry` in remote mode?

### ISSUE THREAD

**Issue by jeffutter** [deivid-rodriguez/byebug#299] opened 2016-11-11 04:18 UTC
## Problem description

Pry doesn't work in remote mode

## Expected behavior

pry to work in remote mode

## Actual behavior

`*** Command is available only in local mode.`

## Steps to reproduce the problem

Connect to a remote session and type `pry`

## Notes

I am looking for a solution do 'remote' debug ruby apps running in a docker-compose setup. Regular pry/pry-byebug won't work since there are a few separate applications and docker has trouble dealing with the stdin/stdout. I tried pry-remote but it just immediately quits when I try to connect, with no error.

A remote byebug session seems to work great, but I miss the niceties I am used to with pry.  I was wondering if anyone can provide some context around why pry won't work in remote mode. Would this be possible to implement? Given some direction as to where to start, I could take a crack at it.

**Comment by deivid-rodriguez** [comment] 2017-12-31 18:49
Hi!

So I had a look at this. The problem is that when you launch a separate REPL from within `byebug`'s prompt, that REPL takes control of user input, so it won't send it to the remote server as byebug does in remote mode.

I think the best way to support this would be to make `pry-byebug` compatible with `pry-remote`, so I'll close this issue and keep track of progress in deivid-rodriguez/pry-byebug#33.

**Closed by deivid-rodriguez** 2017-12-31 18:49 UTC
