### ISSUE TITLE
Update docs regarding printing variables

### ISSUE THREAD

**Issue by hlindberg** [deivid-rodriguez/byebug#217] opened 2016-03-11 18:00 UTC
There seems to be a 'p' command (for print like in 'debugger'), but it results in its argument being printed twice:
```
p 1
1
1
```

**Comment by deivid-rodriguez** [comment] 2016-03-12 16:30
No, there's not. `p` is a Ruby command.

I guess it's both printing the value (what `p` does) and the value returned by the `p` call (done for every command evaluated in byebug's prompt).

Closing since I don't think this is an issue. Reopen if you don't agree.

**Comment by hlindberg** [comment] 2016-03-13 02:54
When using the debugger < ruby 2.0.0, the 'p' is used to print out the value. It is used when you have a variable named like one of the debugger commands - i.e. like 'step'. You quickly get into the habit of always using it to print something (or you accidentally, sometimes will hit one of the commands).

That makes it quite annoying when using this on byebug. I would be great if it did not print out the result of printing, and just printed once.

**Comment by deivid-rodriguez** [comment] 2016-03-13 12:26
I don't know how `debugger` special-cased this, but it doesn't make much sense to me. Printing in a REPL (which already prints by default, the "P" in REPL) seems redundant. So these double prints seem correct.

Also, your reasoning about always using `p` to prevent command collapsing is a bit off, since it will collapse too whenever you have a variable called `p`.

I recommend you use the autoevaluation feature, i.e., use just `1` instead of `p 1`.

**Comment by hlindberg** [comment] 2016-03-13 13:09
Your own guide https://github.com/deivid-rodriguez/byebug/blob/master/GUIDE.md shows `p` in action. The text says that `p` is used to print variables. If I just run the example in that guide `p` prints twice. The guide or the support for `p` is wrong.

**Comment by hlindberg** [comment] 2016-03-13 13:09
I do not have permission to reopen it seems :-)

**Comment by deivid-rodriguez** [comment] 2016-03-13 19:03
Right, so the story goes: I ported the Guide from old debugger. At some point, I removed the debugger command but I didn't update the Guide. As you said, the old command only printed the value once. So there's 2 possible solutions now:

- Update the Guide to print the value twice.
- Update the Guide to use something else to print variables.

Feel free to open a PR fixing this either way.

**Comment by deivid-rodriguez** [comment] 2016-03-13 19:04
> I do not have permission to reopen it seems :-)

Too bad... I reopened for you!

**Comment by hlindberg** [comment] 2016-03-14 14:14
fwiw, `puts` prints the value and `nil`, which slightly better. (The problem with printing twice is mainly when the printed is a big chunk of data, and this makes it harder to scroll back and also harder to find where the output starts).

As with any command (e.g to print a variable), there is always the risk of it shadowing the debugged code. I really do think there should be a debugger way of ensuring that you always invoke the debugger command you intended instead of hitting Ruby in general. (i.e. if "Ruby puts" was overridden I don't want it when I am debugging).

I can help fix and put up a PR, but before doing that:
* do you think adding `p` back as a command is out of the question?
* is something like `=` a reasonable compromise for a "debugger print"?
* should there also be a way of giving commands such that the debugger interpretation always wins (perhaps a setting for those that do not mind using say = p when there is a variable named p)?
* something else?

**Comment by deivid-rodriguez** [comment] 2016-03-14 14:30
> fwiw, puts prints the value and nil, which slightly better.

I guess `puts` returns `nil` and `p` returns the printed value.

> As with any command (e.g to print a variable), there is always the risk of it shadowing the debugged code. I really do think there should be a debugger way of ensuring that you always invoke the debugger command you intended instead of hitting Ruby in general. (i.e. if "Ruby puts" was overridden I don't want it when I am debugging).

I'm not sure I understand this. The current idea is that no debugger commands override any Ruby commands. Not sure if this is currently 100% true, but it's the overall intention. That's part of why I removed the `p` command: preventing surprises.

I'm still not sure why using `eval`, autoevaluation or other mechanism don't work for you. Note that the current behavior is the same in the other Ruby REPL's (`irb` or `pry`).

> do you think adding p back as a command is out of the question?

No, but I'd like a good motivation.

> is something like = a reasonable compromise for a "debugger print"?

You mean a command called `=`? Wouldn't that be the current autoevaluation or `eval`?

> should there also be a way of giving commands such that the debugger interpretation always wins (perhaps a setting for those that do not mind using say = p when there is a variable named p)?

The debugger interpretation currently wins. If you have a variable named `s`, it will step instead of printing the `s` value. You can use Ruby's eval to override this behavior.

**Comment by hlindberg** [comment] 2016-03-14 14:43
Good that debugger wins.

If it was up to me, I would like the `p` back :-) The motivation is:
* you need an authoritative way to print things (i.e determined by the debugger). I may be debugging code written by someone using a lot of meta programming and there may be altered ruby behavior for anything, including `eval`, `puts`, `p` etc. I may not be aware of any of this and end up being confused.
* Using `p` makes bybug compatible with the older debugger (over time that is less of a concern naturally, but when jumping between ruby versions (as I do) it is annoying as you have to actively remember which debugger you are using).
* The commands `s`, `n`, and `p` are the most frequently used (at least by me)

**Comment by deivid-rodriguez** [comment] 2016-03-14 16:29
> you need an authoritative way to print things (i.e determined by the debugger). I may be debugging code written by someone using a lot of meta programming and there may be altered ruby behavior for anything, including eval, puts, p etc. I may not be aware of any of this and end up being confused.

Big no. If the debugged program changes the standard behavior of things, a debugger should help you noticing it, not hide it. Plus, the confusion can happen the other way around: people getting started with `byebug` can get surprised if behavior of standard ruby commands change.

> Using p makes byebug compatible with the older debugger (over time that is less of a concern naturally, but when jumping between ruby versions (as I do) it is annoying as you have to actively remember which debugger you are using).

Compatibility with `debugger` has never been a goal of `byebug`.

> The commands s, n, and p are the most frequently used (at least by me).

Sorry about that. You're a special case, but new developers getting started with `byebug` won't even know there once was a command called `p`.

**Comment by hlindberg** [comment] 2016-03-14 16:40
I disagree strongly about being bit by altered behavior is a good thing - I am trying to debug the thing, I don't want to be bit by it. It does not help me one bit that the debugger does not work when someone "screwed up Ruby" with monkey patches. Also, the code may be an internal DSL where it is supposed to behave differently - I don't want to use the internal DSL's "print" or "p" or "eval" or whatever. That is just wrong.

So, restating, there needs to be an authoritative way of printing, just like an authoritative way of stepping. If it `p` or not is a minor problem in comparison.

**Comment by deivid-rodriguez** [comment] 2016-03-14 16:43
>  It does not help me one bit that the debugger does not work when someone "screwed up Ruby" with monkey patches.

Wow, I thought we were talking about a double print here, not about a broken debugger.

I guess we'll have to agree to disagree! Thanks for your input.

**Comment by hlindberg** [comment] 2016-03-14 17:13
p currently double prints, yes - which is annoying - it is based on "Ruby p". Hence there is no control in the debugger over printing. That is also a problem. The same problem as with any command that is not a debugger command for printing. I can help add one, it does not have to be `p` (although I would prefer that).

You said "big no" to having an authoritative printing command in the debugger. I explained why I think that is not good. I think you agree that an authoritative "step" is needed? Then why is printing different?

**Comment by deivid-rodriguez** [comment] 2016-03-14 18:14
Ruby already has multiple ways of printing things, I don't get why we need an authoritative way of doing it. Or do you want `puts` and `print` and so on added as commands too? You still haven't answered what's wrong with using `eval` or just autoevaluating things. Your original example (`p 1`) is too simple to understand your needs.

In any case, my "big no" answer was meant to point out that I don't agree with the following:

> I may be debugging code written by someone using a lot of meta programming and there may be altered ruby behavior for anything, including eval, puts, p etc. I may not be aware of any of this and end up being confused.

because it seems like trying to fix monkeypatching with monkeypatching.

**Comment by hlindberg** [comment] 2016-03-14 20:07
What people do with monkeypatching is not always wrong in the sense it should be removed/fixed, especially when implementing an internal DSLs (where it may be desirable to prevent as much as possible of Ruby's normal behavior in that DSL).

`eval` certainly works for evaluation/printing (just like puts, p, inspect, etc.), but isn't that also just falling back to Ruby's eval ? Thus there is no print/eval in the debugger itself.

What I am asking for is not monkeypatching monkeypatching, I am asking for some kind of print that always works because the debugger implements it. Now if someone did actually monkeypatch Kernel it is a different thing, but if the current module/class has implemented "print", "puts", "p", etc. you would hit those instead of what you expect. Trying to prevent monkeypatching of Kernel and IO would be quite difficult - so that is not what I am proposing. 

Does that better explain what I am asking for?

**Comment by deivid-rodriguez** [comment] 2016-03-15 08:12
> What people do with monkeypatching is not always wrong in the sense it should be removed/fixed

Agreed.

> eval certainly works for evaluation/printing (just like puts, p, inspect, etc.), but isn't that also just falling back to Ruby's eval ? Thus there is no print/eval in the debugger itself.

Correct, but what `eval` returns is the only thing that gets printed in this case. So you don't get things printed twice, because you don't use a "Ruby printing command".

> What I am asking for is not monkeypatching monkeypatching, I am asking for some kind of print that always works because the debugger implements it.

I think the best fit for your request would be a separate command that doesn't conflict with any standard Ruby command.

> Does that better explain what I am asking for?

Yes, I think so. I still don't see the usefulness of this new command right now. But I will revisit this in the future with an open mind! How's that? In the mean time, I think you can easily extend `byebug` to add this new command. I think it shouldn't be too hard. Let me know if you go with this option and you need any help.

**Comment by hlindberg** [comment] 2016-03-15 14:16
> I think the best fit for your request would be a separate command that doesn't conflict with any standard Ruby command.

yes, exactly, great thanks - that makes it worth while making a PR, will dig into that.

**Comment by deivid-rodriguez** [comment] 2016-03-15 14:48
Thanks.

Just keep in mind that, whereas you'll most likely be able to reuse the command in an extension, I'll most likely won't merge it into `byebug` since I still don't see the usefulness of it.

**Comment by hlindberg** [comment] 2016-03-15 16:16
I did some experiments. And it seems like if I do this:
```
eval print_me
```
Then that does not hit a method named `eval` in my context. But if I do this:
```
eval(print_me)
```
it will. The rule seems to be that if there is a '(' without whitespace then it is a method call in context.

That seems to be the authoritative way I was looking for (except if someone monkeypatches Kernel.eval, but then they should be tarred and feathered).

here is my experiment:
```
class Evil
  def eval(*args)
    print_me = 10
    puts "Mwoah ha ha, ha ha"
  end
  def a_buggy_method(x)
    print_me = 10
    eval x + 1
  end
end

Evil.new.a_buggy_method(42)
```

And then, as you said, I don't really need to do anything except using `eval`.
Now, if I could alias that to my beloved `p` :P ... 

Thanks for sticking with me here!

The resolution of this ticket is to change the guide to use 'eval'. Will edit that and make a PR.

**Comment by deivid-rodriguez** [comment] 2016-03-16 09:05
Thanks for the investigation and the patch. I just reproduced the parenthesis thing, it's very weird to me... I'll investigate why that happens.

**Closed by deivid-rodriguez** 2016-03-16 09:05 UTC

**Comment by hlindberg** [comment] 2016-03-16 11:13
"the parenthesis thing" is actually valuable as a distinction between the "two evals" in my example even if it was unintentional :-)

**Comment by deivid-rodriguez** [comment] 2016-03-16 11:25
Yeah. I'd still like to know the reason... :)
