### ISSUE TITLE
Byebug changes current connection to database

### ISSUE THREAD

**Issue by fabioperrella** [deivid-rodriguez/byebug#184] opened 2015-11-09 11:45 UTC
I'm using byebug 8.0.1 with rails 4.2.0 and ruby 2.1.2p95

I've noticed that when adding a breakpoint, byebug is using a different database connection that rspec used to create the records in db, so it is not possible to find records that were created in rspec transaction

The code I used is this:

```
puts ActiveRecord::Base.connection.__id__
provisioning = Provisioning::Base.find_by(provisioning_id: 111)
byebug
```

The id printed by `puts` is different from the id printed in byebug console (when it reaches the breakpoint)

**Comment by deivid-rodriguez** [comment] 2015-11-09 12:58
Hi, @fabioperrella. This is very unlikely to be `byebug`'s fault. It has nothing to do with databases! 

Maybe you're tests are running in a different thread from the database transaction (see [here](https://github.com/jnicklas/capybara#transactions-and-database-setup) for example.

I'm going to go ahead and close this. Feel free to reopen if you still think this is `byebug`'s fault, but please provide me with a way to reproduce the issue you're seeing.

**Comment by martinstreicher** [comment] 2015-11-10 15:44
I saw this same behavior this week. Trying to print anything from ActiveRecord from the byebug prompt missed data or caused hangs. I am not sure of the cause. I am guessing when it hangs one transaction is still open while another is trying to start.

@fabioperrella Did you find any other culprit? Are you using Database Cleaner?

**Comment by fabioperrella** [comment] 2015-11-10 15:58
I will try to reproduce it in a new project, maybe any of my project dependencies is causing this error
I'm not using database cleaner

**Comment by deivid-rodriguez** [comment] 2015-11-10 15:59
@martinstreicher That is weird. The only thing I can think of is that your ruby is missing this (unreleased) patch: https://github.com/ruby/ruby/commit/2d4bc584eef5dcd11dbae4c92fe8b404f054ff46. This has caused some problems in byebug's tests, but neither @k0kubun or myself have found any "real world" situations where it manifests as a problem.

@martinstreicher @fabioperrella Perhaps you could try applying the patch to your ruby version and see if that fixes the issue... See [here](https://github.com/deivid-rodriguez/byebug/blob/master/.travis.yml#L14-L15) for `rvm` instructions. I'm not very optimistic about that fixing your issue, but it won't do any harm for sure.

**Comment by k0kubun** [comment] 2015-11-10 16:19
> I saw this same behavior this week. Trying to print anything from ActiveRecord from the byebug prompt missed data or caused hangs.

I want to see the detail log of "hangs". Is it SEGV? And is it reproductive in byebug 6.0 too?

**Comment by martinstreicher** [comment] 2015-11-10 16:25
I get two different issues. 

1/ If I set the database_cleaner technique to transaction, and then try to do anything with the database in AR using byebug, the call to the database hangs. I can see two sleeping PostgreSQL processes using ps. Killing those terminates the connection and returns control to byebug. 

2/ If I set the cleaner technique to truncation, byebug lets me use the database, but a continue in byebug then crashes with a SEGV. 

Would you like to see the SEGV in (2)? 

I just built ruby-head in RVM and will try things there.

**Comment by deivid-rodriguez** [comment] 2015-11-10 16:32
> I just built ruby-head in RVM and will try things there.

Crossing fingers.... :pray:

**Comment by martinstreicher** [comment] 2015-11-10 16:32
Installing ruby-head from RVM and running all gems with it avoids the crash I mentioned just a moment ago. 

However, the data created for my spec test does not show up at the byebug command-line. The data created before the spec appears, but not the data in the spec. 

I realize this may not be byebug’s fault, but it is odd behavior.

**Comment by deivid-rodriguez** [comment] 2015-11-10 16:38
> Installing ruby-head from RVM and running all gems with it avoids the crash I mentioned just a moment ago. 

Sweet. :smile: 

> However, the data created for my spec test does not show up at the byebug command-line. The data created before the spec appears, but not the data in the spec.

I think this might be due to how transactions work. If you are inside a transaction and whatever you are evaluating in `byebug`'s prompt touches the database to ask for data that was created inside the transaction, it won't show up because the data has not been actually committed. If you switch the strategy to truncation it should work the way you want.

**Comment by djbender** [comment] 2015-11-11 16:51
To Deivid and all the other maintainers, thank you so much for all your time and effort on byebug! It is very much appreciated.

I saw similar behavior to the description after upgrading to v8 from v6.x.x. After a session of git bisect I was able to pinpoint the commit that introduced the change in behavior I'm seeing where the databases are already cleared (even in the middle of them): 634559cb. Seems like this is definitely related to evals happening in new threads.

What I would like to be able to do is have someway to inspect the database during a spec to see what state the test database is in. Is there a way to do that now?

Thanks again!

**Comment by deivid-rodriguez** [comment] 2015-11-11 17:45
@djbender Thanks for the kudos in for the "bisection". :smile: 

So this is an unintented regression then (and that causes other problems too like #188). The most straighforward way to get this back would be to revert that commit and provide the subdebuggers functionality in a different command. But I want to explore other options to see if I can keep everything working as it is.

I'll let you know.

**Comment by deivid-rodriguez** [comment] 2015-11-11 23:12
@djbender Try last master and check if this is fixed, please.

**Comment by martinstreicher** [comment] 2015-11-11 23:13
I will try it shortly, too.

**Comment by deivid-rodriguez** [comment] 2015-11-11 23:14
:+1:

**Comment by martinstreicher** [comment] 2015-11-12 14:08
I continue to get a SEGV using Ruby 2.2.3 and the master branch of this gem.

**Comment by deivid-rodriguez** [comment] 2015-11-12 14:31
Yeah, the crash does not depend on `byebug`, you need to install either `ruby-head` or `2.2.3` / `2.1.7` with the patch I pointed out earlier.

**Comment by martinstreicher** [comment] 2015-11-12 14:46
ruby-head works fine.

**Comment by deivid-rodriguez** [comment] 2015-11-12 15:01
With "works fine" you mean it does not SEGV or that you can also see the data?

Also, note that altough ruby's trunk stability is very good, if you don't want to use `ruby-head` you can also install the single patch that's needed. For example, in `rvm`

```
rvm reinstall 2.2.3 --patch https://github.com/ruby/ruby/commit/2d4bc584eef5dcd11dbae4c92fe8b.patch
```

**Comment by martinstreicher** [comment] 2015-11-12 15:06
In 2.2.3: I can see the data but it SEGVs when I hit continue. 

In 2.3.0dev: I can see the data, and no SEGV.

**Comment by deivid-rodriguez** [comment] 2015-11-12 15:07
`2.2.3` without the patch I assume?

**Comment by martinstreicher** [comment] 2015-11-12 15:24
yes

**Comment by deivid-rodriguez** [comment] 2015-11-12 15:31
Perfect, closing then. Thanks for the feedback!

**Closed by deivid-rodriguez** 2015-11-12 15:31 UTC

**Comment by djbender** [comment] 2015-11-12 17:18
for what it's worth, the workaround previously suggested worked: https://github.com/jnicklas/capybara#transactions-and-database-setup

I'll scope out master soon.

**Comment by djbender** [comment] 2015-11-16 23:48
v8.2.0 (w/ 4e6a5ea) resolves this.

thank you much! :100:

**Comment by fabioperrella** [comment] 2015-11-17 10:45
:+1:
